name: build

on:
  workflow_call:
    inputs:
      os:
        description: '运行在哪个操作系统镜像上'
        type: string
        required: true
      python-version:
        description: 'python的版本'
        type: string
        required: true
jobs:

  build:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
      - name: setup python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: 构建项目
        run: |
          poetry build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dist
          path: ./dist
          ignore: true