name: Build

on: 
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version: [ "3.8","3.9", "3.10", "3.11.3", "3.12" ]
    uses: ./.github/workflows/reuse/build.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}


 

  