# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  test:
    uses: ./.github/workflows/test.yml


  deploy:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Poetry Install
      run: |
        pipx install poetry

    - name: Install dependencies
      # 设置POETRY_PYPI_TOKEN_PYPI 环境变量
      run: |
        poetry install
    
    - name: 如果是release触发，那么就用tag名
      if: github.event_name == 'release'
      run: |
        echo "poetry version ${{github.ref}}"
        # poetry version ${{ github.ref }}

    - name: 如果是workflow触发，那么就用inputs.version
      # 设置POETRY_PYPI_TOKEN_PYPI 环境变量
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "poetry version ${{ inputs.version }}"
        # poetry version ${{ inputs.version }}

    - name: 自动提交toml
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: 版本号变更
        file_pattern: pyproject.toml

    - name: Poetry publish
      # 设置POETRY_PYPI_TOKEN_PYPI 环境变量
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry build
        # poetry publish

    - name: 上传构建产物
      uses: actions/upload-artifact@v4.3.1
      with:
        name: dist
        path: ./dist/*
