name: Python package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8" ]
        os: [rakha786/microsoftoffice]
    uses: ./.github/workflows/resuse-build-workflow.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}