name: test

on:
  workflow_call:
    inputs:
      os:
        description: '运行在哪个操作系统镜像上'
        type: string
        required: true
        default: ubuntue-latest
      python-version:
        description: 'python的版本'
        type: string
        required: true
        default: "3.8"
jobs:

  test:
    runs-on: ${{ inputs.os }}
    
    steps:
      - uses: actions/checkout@v3
      - name: 安装python环境 ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          cache-name: ${{inputs.os}}-${{inputs.python-version}}

      - name: Install dependencies
        run: poetry install
                  
      - name: Unittest单元测试
        run: |
          poetry run python -m unittest discover test -v

