name: Test

on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version: [ "3.8","3.9", "3.10","3.11.3","3.12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          
      - name: Install dependencies
        run: poetry install
                  
      - name: Unittest
        run: |
          poetry run coverage run -m unittest discover test -v
          poetry run coverage report
          poetry run coverage xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
          with:
            name: coverage
            path: ./coverage.xml
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
          with:
            name: coverage
      - name: coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

 

  